/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.parser;

import org.sablecc.sablecc.node.*;
import org.sablecc.sablecc.analysis.*;



class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTPkgId(TPkgId node)
    {
        index = 0;
    }

    public void caseTPackage(TPackage node)
    {
        index = 1;
    }

    public void caseTStates(TStates node)
    {
        index = 2;
    }

    public void caseTHelpers(THelpers node)
    {
        index = 3;
    }

    public void caseTTokens(TTokens node)
    {
        index = 4;
    }

    public void caseTIgnored(TIgnored node)
    {
        index = 5;
    }

    public void caseTProductions(TProductions node)
    {
        index = 6;
    }

    public void caseTTokenSpecifier(TTokenSpecifier node)
    {
        index = 7;
    }

    public void caseTProductionSpecifier(TProductionSpecifier node)
    {
        index = 8;
    }

    public void caseTDot(TDot node)
    {
        index = 9;
    }

    public void caseTDDot(TDDot node)
    {
        index = 10;
    }

    public void caseTSemicolon(TSemicolon node)
    {
        index = 11;
    }

    public void caseTEqual(TEqual node)
    {
        index = 12;
    }

    public void caseTLBkt(TLBkt node)
    {
        index = 13;
    }

    public void caseTRBkt(TRBkt node)
    {
        index = 14;
    }

    public void caseTLAbkt(TLAbkt node)
    {
        index = 15;
    }

    public void caseTRAbkt(TRAbkt node)
    {
        index = 16;
    }

    public void caseTLPar(TLPar node)
    {
        index = 17;
    }

    public void caseTRPar(TRPar node)
    {
        index = 18;
    }

    public void caseTLBrace(TLBrace node)
    {
        index = 19;
    }

    public void caseTRBrace(TRBrace node)
    {
        index = 20;
    }

    public void caseTPlus(TPlus node)
    {
        index = 21;
    }

    public void caseTMinus(TMinus node)
    {
        index = 22;
    }

    public void caseTQMark(TQMark node)
    {
        index = 23;
    }

    public void caseTStar(TStar node)
    {
        index = 24;
    }

    public void caseTBar(TBar node)
    {
        index = 25;
    }

    public void caseTComma(TComma node)
    {
        index = 26;
    }

    public void caseTSlash(TSlash node)
    {
        index = 27;
    }

    public void caseTRArrow(TRArrow node)
    {
        index = 28;
    }

    public void caseTLArrow(TLArrow node)
    {
        index = 29;
    }

    public void caseTChain(TChain node)
    {
        index = 30;
    }

    public void caseTCustomheritage(TCustomheritage node)
    {
        index = 31;
    }

    public void caseTMaketree(TMaketree node)
    {
        index = 32;
    }

    public void caseTNocreate(TNocreate node)
    {
        index = 33;
    }

    public void caseTColon(TColon node)
    {
        index = 34;
    }

    public void caseTExclam(TExclam node)
    {
        index = 35;
    }

    public void caseTInherit(TInherit node)
    {
        index = 36;
    }

    public void caseTDerive(TDerive node)
    {
        index = 37;
    }

    public void caseTId(TId node)
    {
        index = 38;
    }

    public void caseTExternalName(TExternalName node)
    {
        index = 39;
    }

    public void caseTChar(TChar node)
    {
        index = 40;
    }

    public void caseTDecChar(TDecChar node)
    {
        index = 41;
    }

    public void caseTHexChar(THexChar node)
    {
        index = 42;
    }

    public void caseTString(TString node)
    {
        index = 43;
    }

    public void caseEOF(EOF node)
    {
        index = 44;
    }
}
