<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0" name="org" nsURI="http://www.tu-dresden.de" nsPrefix="tudresden">
  <eSubpackages name="ocl20" nsURI="http://www.tu-dresden.de/ocl20" nsPrefix="ocl20">
    <eSubpackages name="pivot" nsURI="http://www.tu-dresden.de/ocl20/pivot" nsPrefix="dresdenocl">
      <eSubpackages name="modelinstancetype" nsURI="http://www.tudresden.de/ocl20/pivot/modelinstancetype" nsPrefix="modelinstancetype">
        <eSubpackages name="test" nsURI="http://www.tudresden.de/ocl20/pivot/modelinstancetype/test" nsPrefix="test">
          <eSubpackages name="testmodel" nsURI="http://www.tudresden.de/ocl20/pivot/modelinstancetype/test/testmodel" nsPrefix="testmodel">
            <eClassifiers xsi:type="ecore:EClass" name="ContainerClass">
              <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypeProviderClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/PrimitiveTypeProviderClass" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="collectionTypeProviderClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/CollectionTypeProviderClass" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationLiteralProviderClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/EnumerationLiteralProviderClass" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="class1Instances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="class2Instances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class2" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="interface1Instances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface1" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="interface2Instances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface2" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="interface3Instances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface3" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="copyableClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/CopyableClass" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="nonCopyableClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/NonCopyableClass" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="staticPropertyAndOperationClassInstances" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/StaticPropertyAndOperationClass" containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeProviderClass">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanProperty1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerProperty1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="realProperty1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringProperty1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeProviderClass">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagProperty1" ordered="false" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderedSetProperty1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceProperty1" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="setProperty1" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteralProviderClass">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerationLiteralProperty1" ordered="false" unique="false" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Enumeration1"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="Enumeration1">
              <eLiterals name="Literal1"/>
              <eLiterals name="Literal2"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="Class1">
              <eOperations name="voidOperation"/>
              <eOperations name="nonMultipleOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              <eOperations name="multipleUniqueOrderedOperation" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eOperations name="multipleUniqueUnorderedOperation" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eOperations name="multipleNonuniqueOrderedOperation" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eOperations name="multipleNonuniqueUnorderedOperation" ordered="false" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eOperations name="voidOperationWithBooleanArgument">
                <eParameters name="arg1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              </eOperations>
              <eOperations name="voidOperationWithBooleanMultipleArgument">
                <eParameters name="arg1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              </eOperations>
              <eOperations name="voidOperationWithStringArgument">
                <eParameters name="arg1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              </eOperations>
              <eOperations name="voidOperationWithStringMultipleArgument">
                <eParameters name="arg1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              </eOperations>
              <eOperations name="voidOperationWithObjectArgument">
                <eParameters name="arg1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
              </eOperations>
              <eOperations name="voidOperationWithObjectMultipleArgument">
                <eParameters name="arg1" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
              </eOperations>
              <eOperations name="voidOperationWithEnumerationLiteralArgument">
                <eParameters name="arg1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Enumeration1"/>
              </eOperations>
              <eOperations name="voidOperationWithEnumerationLiteralMultipleArgument">
                <eParameters name="arg1" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Enumeration1"/>
              </eOperations>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonMultipleProperty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleUniqueOrderedProperty" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleUniqueUnorderedProperty" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleNonuniqueOrderedProperty" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleNonuniqueUnorderedProperty" ordered="false" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyBooleanNonMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyStringNonMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyBooleanMultiple" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyStringMultiple" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPropertyObjectNonMultiple" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPropertyObjectMultiple" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyEnumerationLiteralNonMultiple" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Enumeration1"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentPropertyEnumerationLiteralMultiple" upperBound="-1" eType="#//ocl20/pivot/modelinstancetype/test/testmodel/Enumeration1"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="Class2" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
            <eClassifiers xsi:type="ecore:EClass" name="Interface1" abstract="true" interface="true"/>
            <eClassifiers xsi:type="ecore:EClass" name="Interface2" abstract="true" interface="true"/>
            <eClassifiers xsi:type="ecore:EClass" name="Interface3" abstract="true" interface="true" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface2"/>
            <eClassifiers xsi:type="ecore:EClass" name="CopyableClass"/>
            <eClassifiers xsi:type="ecore:EClass" name="C1Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
            <eClassifiers xsi:type="ecore:EClass" name="I1I2Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface1 #//ocl20/pivot/modelinstancetype/test/testmodel/Interface2"/>
            <eClassifiers xsi:type="ecore:EClass" name="I1Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface1"/>
            <eClassifiers xsi:type="ecore:EClass" name="I2C1Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface2 #//ocl20/pivot/modelinstancetype/test/testmodel/Class1"/>
            <eClassifiers xsi:type="ecore:EClass" name="I3C2Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Class2 #//ocl20/pivot/modelinstancetype/test/testmodel/Interface3"/>
            <eClassifiers xsi:type="ecore:EClass" name="I3Implementation" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/Interface3"/>
            <eClassifiers xsi:type="ecore:EClass" name="ClonableCopyableClass" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/CopyableClass"/>
            <eClassifiers xsi:type="ecore:EClass" name="InitializableCopyableClass" eSuperTypes="#//ocl20/pivot/modelinstancetype/test/testmodel/CopyableClass"/>
            <eClassifiers xsi:type="ecore:EClass" name="NonCopyableClass"/>
            <eClassifiers xsi:type="ecore:EClass" name="StaticPropertyAndOperationClass"/>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
