/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}

