/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class AIntervalSet extends PSet
{
    private TLBkt _lBkt_;
    private PChar _left_;
    private TDDot _dDot_;
    private PChar _right_;
    private TRBkt _rBkt_;

    public AIntervalSet()
    {
    }

    public AIntervalSet(
        TLBkt _lBkt_,
        PChar _left_,
        TDDot _dDot_,
        PChar _right_,
        TRBkt _rBkt_)
    {
        setLBkt(_lBkt_);

        setLeft(_left_);

        setDDot(_dDot_);

        setRight(_right_);

        setRBkt(_rBkt_);

    }
    public Object clone()
    {
        return new AIntervalSet(
            (TLBkt) cloneNode(_lBkt_),
            (PChar) cloneNode(_left_),
            (TDDot) cloneNode(_dDot_),
            (PChar) cloneNode(_right_),
            (TRBkt) cloneNode(_rBkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntervalSet(this);
    }

    public TLBkt getLBkt()
    {
        return _lBkt_;
    }

    public void setLBkt(TLBkt node)
    {
        if(_lBkt_ != null)
        {
            _lBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBkt_ = node;
    }

    public PChar getLeft()
    {
        return _left_;
    }

    public void setLeft(PChar node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TDDot getDDot()
    {
        return _dDot_;
    }

    public void setDDot(TDDot node)
    {
        if(_dDot_ != null)
        {
            _dDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dDot_ = node;
    }

    public PChar getRight()
    {
        return _right_;
    }

    public void setRight(PChar node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public TRBkt getRBkt()
    {
        return _rBkt_;
    }

    public void setRBkt(TRBkt node)
    {
        if(_rBkt_ != null)
        {
            _rBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBkt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBkt_)
            + toString(_left_)
            + toString(_dDot_)
            + toString(_right_)
            + toString(_rBkt_);
    }

    void removeChild(Node child)
    {
        if(_lBkt_ == child)
        {
            _lBkt_ = null;
            return;
        }

        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_dDot_ == child)
        {
            _dDot_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

        if(_rBkt_ == child)
        {
            _rBkt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBkt_ == oldChild)
        {
            setLBkt((TLBkt) newChild);
            return;
        }

        if(_left_ == oldChild)
        {
            setLeft((PChar) newChild);
            return;
        }

        if(_dDot_ == oldChild)
        {
            setDDot((TDDot) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PChar) newChild);
            return;
        }

        if(_rBkt_ == oldChild)
        {
            setRBkt((TRBkt) newChild);
            return;
        }

    }
}
