<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="package3"
    nsURI="package3" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="TestReferredType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testTypeClass1" eType="ecore:EClass testModel.ecore#//package2/TestTypeClass1"/>
  </eClassifiers>
</ecore:EPackage>
