<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tudresden"
    nsURI="http://www.tu-dresden.de" nsPrefix="tudresden">
  <eSubpackages name="ocl20" nsURI="http://www.tu-dresden.de/ocl20" nsPrefix="ocl20">
    <eSubpackages name="pivot" nsURI="http://www.tu-dresden.de/ocl20/pivot" nsPrefix="pivot">
      <eSubpackages name="examples" nsURI="http://www.tu-dresden.de/ocl20/pivot/examples"
          nsPrefix="examples">
        <eSubpackages name="simple" nsURI="http://www.tu-dresden.de/ocl20/pivot/examples/simple"
            nsPrefix="simple">
          <eClassifiers xsi:type="ecore:EClass" name="Person">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//ocl20/pivot/examples/simple/Person"/>
          <eClassifiers xsi:type="ecore:EClass" name="Professor" eSuperTypes="#//ocl20/pivot/examples/simple/Person"/>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
