<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes" nsURI="http://www.tu-dresden.de/ocl20/pivot/2007/datatypes"
    nsPrefix="datatypes">
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Real" instanceClassName="float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UnlimitedNatural" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Sequence" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bag" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Set" instanceClassName="java.util.Set"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OrderedSet" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
</ecore:EPackage>
