/* Generated by Together */

package com.togethersoft.modules.ocl.test;
import com.togethersoft.openapi.ide.IdeScript;
import com.togethersoft.openapi.ide.IdeContext;
import com.togethersoft.openapi.ide.message.IdeMessageManagerAccess;
import com.togethersoft.openapi.ide.message.IdeMessageType;

abstract public class MyTest implements IdeScript {

    abstract public void run(IdeContext ideContext);

    protected String testResult = "";

    public void printResult(String wanted, String result) {
        String msg = wanted + " : " + result;
        printResult(msg);
    }

    public void printResult(String msg) {
	    IdeMessageManagerAccess.printMessage(IdeMessageType.INFORMATION, msg);
        testResult += msg+"\n";
    }

    public void printSummary() {
	    IdeMessageManagerAccess.printMessage(IdeMessageType.INFORMATION_MODAL, testResult);
    }

    public void clearBuffer() {
        testResult = "";
    }


}

