<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tracermodel"
    nsURI="http://www.tu-dresden.de/ocl20/pivot/2011/tracermodel" nsPrefix="tracermodel">
  <eClassifiers xsi:type="ecore:EClass" name="TracerItem">
    <eOperations name="hasChildren" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="#//OclAny"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TracerItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TracerItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OclAny" instanceClassName="tudresden.ocl20.pivot.essentialocl.standardlibrary.OclAny"/>
</ecore:EPackage>
