<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tudresden"
    nsURI="http://www.tu-dresden.de" nsPrefix="tudresden">
  <eSubpackages name="ocl20" nsURI="http://www.tu-dresden.de/ocl20" nsPrefix="ocl20">
    <eSubpackages name="pivot" nsURI="http://www.tu-dresden.de/ocl20/pivot" nsPrefix="pivot">
      <eSubpackages name="examples" nsURI="http://www.tu-dresden.de/ocl20/pivot/examples"
          nsPrefix="examples">
        <eSubpackages name="pml" nsURI="http://www.tu-dresden.de/ocl20/pivot/examples/pml"
            nsPrefix="pml">
          <eClassifiers xsi:type="ecore:EClass" name="Feature">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="plugins" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Plugin" containment="true" eOpposite="#//ocl20/pivot/examples/pml/Plugin/feature"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Plugin">
            <eOperations name="getNameOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
              <eParameters name="feature" eType="#//ocl20/pivot/examples/pml/Feature"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//ocl20/pivot/examples/pml/Feature"
                eOpposite="#//ocl20/pivot/examples/pml/Feature/plugins"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoints"
                upperBound="-1" eType="#//ocl20/pivot/examples/pml/ExtensionPoint"
                containment="true" eOpposite="#//ocl20/pivot/examples/pml/ExtensionPoint/plugin"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Extension" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="activator" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ExtensionPoint">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="plugin" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/Plugin" transient="true" eOpposite="#//ocl20/pivot/examples/pml/Plugin/extensionPoints"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Extension">
            <eStructuralFeatures xsi:type="ecore:EReference" name="implementation"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoint"
                lowerBound="1" eType="#//ocl20/pivot/examples/pml/ExtensionPoint"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="JavaType">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullyQualifiedName"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Operation" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Operation">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Parameter" containment="true" eOpposite="#//ocl20/pivot/examples/pml/Parameter/operation"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="myType" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Parameter">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/JavaType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
                eType="#//ocl20/pivot/examples/pml/Operation" transient="true" eOpposite="#//ocl20/pivot/examples/pml/Operation/parameters"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PluginPackage">
            <eStructuralFeatures xsi:type="ecore:EReference" name="plugins" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Plugin" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/JavaType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
                eType="#//ocl20/pivot/examples/pml/Feature" containment="true"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
