/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import java.util.*;
import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class AColumnSelectSubListItem extends PSelectSubListItem
{
    private PColumn _column_;

    public AColumnSelectSubListItem()
    {
    }

    public AColumnSelectSubListItem(
        PColumn _column_)
    {
        setColumn(_column_);

    }
    public Object clone()
    {
        return new AColumnSelectSubListItem(
            (PColumn) cloneNode(_column_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColumnSelectSubListItem(this);
    }

    public PColumn getColumn()
    {
        return _column_;
    }

    public void setColumn(PColumn node)
    {
        if(_column_ != null)
        {
            _column_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _column_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_column_);
    }

    void removeChild(Node child)
    {
        if(_column_ == child)
        {
            _column_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_column_ == oldChild)
        {
            setColumn((PColumn) newChild);
            return;
        }

    }
}
