/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import java.util.*;
import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class AEmptySelectList extends PSelectList
{

    public AEmptySelectList()
    {
    }
    public Object clone()
    {
        return new AEmptySelectList();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptySelectList(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
