/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import java.util.*;
import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class AInBooleanExpression extends PBooleanExpression
{
    private PUnaryExpression _unaryExpression_;
    private PQueryExpression _queryExpression_;

    public AInBooleanExpression()
    {
    }

    public AInBooleanExpression(
        PUnaryExpression _unaryExpression_,
        PQueryExpression _queryExpression_)
    {
        setUnaryExpression(_unaryExpression_);

        setQueryExpression(_queryExpression_);

    }
    public Object clone()
    {
        return new AInBooleanExpression(
            (PUnaryExpression) cloneNode(_unaryExpression_),
            (PQueryExpression) cloneNode(_queryExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInBooleanExpression(this);
    }

    public PUnaryExpression getUnaryExpression()
    {
        return _unaryExpression_;
    }

    public void setUnaryExpression(PUnaryExpression node)
    {
        if(_unaryExpression_ != null)
        {
            _unaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExpression_ = node;
    }

    public PQueryExpression getQueryExpression()
    {
        return _queryExpression_;
    }

    public void setQueryExpression(PQueryExpression node)
    {
        if(_queryExpression_ != null)
        {
            _queryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _queryExpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_unaryExpression_)
            + toString(_queryExpression_);
    }

    void removeChild(Node child)
    {
        if(_unaryExpression_ == child)
        {
            _unaryExpression_ = null;
            return;
        }

        if(_queryExpression_ == child)
        {
            _queryExpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_unaryExpression_ == oldChild)
        {
            setUnaryExpression((PUnaryExpression) newChild);
            return;
        }

        if(_queryExpression_ == oldChild)
        {
            setQueryExpression((PQueryExpression) newChild);
            return;
        }

    }
}
