/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import java.util.*;
import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class ANotBooleanExpression extends PBooleanExpression
{
    private PBooleanExpression _booleanExpression_;

    public ANotBooleanExpression()
    {
    }

    public ANotBooleanExpression(
        PBooleanExpression _booleanExpression_)
    {
        setBooleanExpression(_booleanExpression_);

    }
    public Object clone()
    {
        return new ANotBooleanExpression(
            (PBooleanExpression) cloneNode(_booleanExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotBooleanExpression(this);
    }

    public PBooleanExpression getBooleanExpression()
    {
        return _booleanExpression_;
    }

    public void setBooleanExpression(PBooleanExpression node)
    {
        if(_booleanExpression_ != null)
        {
            _booleanExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _booleanExpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_booleanExpression_);
    }

    void removeChild(Node child)
    {
        if(_booleanExpression_ == child)
        {
            _booleanExpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_booleanExpression_ == oldChild)
        {
            setBooleanExpression((PBooleanExpression) newChild);
            return;
        }

    }
}
