/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import java.util.*;
import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class AParUnaryExpression extends PUnaryExpression
{
    private PUnaryExpression _unaryExpression_;

    public AParUnaryExpression()
    {
    }

    public AParUnaryExpression(
        PUnaryExpression _unaryExpression_)
    {
        setUnaryExpression(_unaryExpression_);

    }
    public Object clone()
    {
        return new AParUnaryExpression(
            (PUnaryExpression) cloneNode(_unaryExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParUnaryExpression(this);
    }

    public PUnaryExpression getUnaryExpression()
    {
        return _unaryExpression_;
    }

    public void setUnaryExpression(PUnaryExpression node)
    {
        if(_unaryExpression_ != null)
        {
            _unaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_unaryExpression_);
    }

    void removeChild(Node child)
    {
        if(_unaryExpression_ == child)
        {
            _unaryExpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_unaryExpression_ == oldChild)
        {
            setUnaryExpression((PUnaryExpression) newChild);
            return;
        }

    }
}
