/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class TIntersect extends Token
{
    public TIntersect()
    {
        super.setText("intersect");
    }

    public TIntersect(int line, int pos)
    {
        super.setText("intersect");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIntersect(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntersect(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TIntersect text.");
    }
}
