/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class X2PBooleanExpression extends XPBooleanExpression
{
    private PBooleanExpression _pBooleanExpression_;

    public X2PBooleanExpression()
    {
    }

    public X2PBooleanExpression(
        PBooleanExpression _pBooleanExpression_)
    {
        setPBooleanExpression(_pBooleanExpression_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PBooleanExpression getPBooleanExpression()
    {
        return _pBooleanExpression_;
    }

    public void setPBooleanExpression(PBooleanExpression node)
    {
        if(_pBooleanExpression_ != null)
        {
            _pBooleanExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pBooleanExpression_ = node;
    }

    void removeChild(Node child)
    {
        if(_pBooleanExpression_ == child)
        {
            _pBooleanExpression_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pBooleanExpression_);
    }
}
