/* This file was generated by SableCC (http://www.sablecc.org/). */

package tudresden.ocl.codegen.decl.treegen.node;

import tudresden.ocl.codegen.decl.treegen.analysis.*;

public final class X2PUnaryExpression extends XPUnaryExpression
{
    private PUnaryExpression _pUnaryExpression_;

    public X2PUnaryExpression()
    {
    }

    public X2PUnaryExpression(
        PUnaryExpression _pUnaryExpression_)
    {
        setPUnaryExpression(_pUnaryExpression_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PUnaryExpression getPUnaryExpression()
    {
        return _pUnaryExpression_;
    }

    public void setPUnaryExpression(PUnaryExpression node)
    {
        if(_pUnaryExpression_ != null)
        {
            _pUnaryExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pUnaryExpression_ = node;
    }

    void removeChild(Node child)
    {
        if(_pUnaryExpression_ == child)
        {
            _pUnaryExpression_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pUnaryExpression_);
    }
}
