<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metric"
    nsURI="http://www.dresden-ocl.org/metrics/" nsPrefix="metric">
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eOperations name="getReport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelMetric" eSuperTypes="#//ConstraintMetric">
    <eOperations name="getConstraintCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;return this.getConstraintMetrics().size();&#xD;&#xA;"/>
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getExpressionCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;int result = 0;&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;for ( org.dresdenocl.metrics.metric.ConstraintMetric metric : this.getConstraintMetrics())&#xD;&#xA;&#x9;&#x9;&#x9;result += metric.getExpressionCount();&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;// end for.&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;return result;&#xD;&#xA;"/>
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAvgExpressionCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;return this.getExpressionCount() / this.getConstraintCount();&#xD;&#xA;"/>
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAvgExpressionDepth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;int totalDepth = 0;&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;for ( org.dresdenocl.metrics.metric.ConstraintMetric metric : this.getConstraintMetrics())&#xD;&#xA;&#x9;&#x9;&#x9;totalDepth += metric.getExpressionDepth();&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;// end for.&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;return totalDepth / this.getConstraintCount();&#xD;&#xA;"/>
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getMinExpressionCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getMinExpressionDepth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getMaxExpressionCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getMaxExpressionDepth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getMeanExpressionCount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getMeanExpressionDepth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredModelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintCountPerKind"
        eType="#//ConstraintCount" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintMetrics" upperBound="-1"
        eType="#//ConstraintMetric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintCount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EEnum ../../tudresden.ocl20.pivot.pivotmodel/model/pivotmodel.ecore#//ConstraintKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintMetric" eSuperTypes="#//Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionDepth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calledOperations" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredConstraint" eType="ecore:EClass ../../tudresden.ocl20.pivot.pivotmodel/model/pivotmodel.ecore#//Constraint"/>
  </eClassifiers>
</ecore:EPackage>
