/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.AAstType;
import org.sablecc.sablecc.node.Node;
import org.sablecc.sablecc.node.PAstType;
import org.sablecc.sablecc.node.PExternalName;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.TLAbkt;
import org.sablecc.sablecc.node.TRAbkt;



public final class AAstType extends PAstType
{
    private TLAbkt _lAbkt_;
    private PExternalName _externalName_;
    private TRAbkt _rAbkt_;

    public AAstType()
    {
    }

    public AAstType(
        TLAbkt _lAbkt_,
        PExternalName _externalName_,
        TRAbkt _rAbkt_)
    {
        setLAbkt(_lAbkt_);

        setExternalName(_externalName_);

        setRAbkt(_rAbkt_);

    }
    public Object clone()
    {
        return new AAstType(
            (TLAbkt) cloneNode(_lAbkt_),
            (PExternalName) cloneNode(_externalName_),
            (TRAbkt) cloneNode(_rAbkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAstType(this);
    }

    public TLAbkt getLAbkt()
    {
        return _lAbkt_;
    }

    public void setLAbkt(TLAbkt node)
    {
        if(_lAbkt_ != null)
        {
            _lAbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lAbkt_ = node;
    }

    public PExternalName getExternalName()
    {
        return _externalName_;
    }

    public void setExternalName(PExternalName node)
    {
        if(_externalName_ != null)
        {
            _externalName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _externalName_ = node;
    }

    public TRAbkt getRAbkt()
    {
        return _rAbkt_;
    }

    public void setRAbkt(TRAbkt node)
    {
        if(_rAbkt_ != null)
        {
            _rAbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rAbkt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lAbkt_)
            + toString(_externalName_)
            + toString(_rAbkt_);
    }

    void removeChild(Node child)
    {
        if(_lAbkt_ == child)
        {
            _lAbkt_ = null;
            return;
        }

        if(_externalName_ == child)
        {
            _externalName_ = null;
            return;
        }

        if(_rAbkt_ == child)
        {
            _rAbkt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lAbkt_ == oldChild)
        {
            setLAbkt((TLAbkt) newChild);
            return;
        }

        if(_externalName_ == oldChild)
        {
            setExternalName((PExternalName) newChild);
            return;
        }

        if(_rAbkt_ == oldChild)
        {
            setRAbkt((TRAbkt) newChild);
            return;
        }

    }
}
