/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.TQMark;
import org.sablecc.sablecc.node.Token;



public final class TQMark extends Token
{
    public TQMark()
    {
        super.setText("?");
    }

    public TQMark(int line, int pos)
    {
        super.setText("?");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TQMark(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQMark(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TQMark text.");
    }
}
