/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Node;
import org.sablecc.sablecc.node.PStateListTail;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.XPStateListTail;

public final class X1PStateListTail extends XPStateListTail
{
    private XPStateListTail _xPStateListTail_;
    private PStateListTail _pStateListTail_;

    public X1PStateListTail()
    {
    }

    public X1PStateListTail(
        XPStateListTail _xPStateListTail_,
        PStateListTail _pStateListTail_)
    {
        setXPStateListTail(_xPStateListTail_);
        setPStateListTail(_pStateListTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPStateListTail getXPStateListTail()
    {
        return _xPStateListTail_;
    }

    public void setXPStateListTail(XPStateListTail node)
    {
        if(_xPStateListTail_ != null)
        {
            _xPStateListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPStateListTail_ = node;
    }

    public PStateListTail getPStateListTail()
    {
        return _pStateListTail_;
    }

    public void setPStateListTail(PStateListTail node)
    {
        if(_pStateListTail_ != null)
        {
            _pStateListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pStateListTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPStateListTail_ == child)
        {
            _xPStateListTail_ = null;
        }

        if(_pStateListTail_ == child)
        {
            _pStateListTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPStateListTail_) +
            toString(_pStateListTail_);
    }
}
