/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.node.Cast;
import org.sablecc.sablecc.node.NoCast;

public class NoCast implements Cast
{
    public final static NoCast instance = new NoCast();

    private NoCast()
    {
    }

    public Object cast(Object o)
    {
        return o;
    }
}
