/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.node.Switch;

public interface Switchable
{
    void apply(Switch sw);
}
