/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.TIgnored;
import org.sablecc.sablecc.node.Token;



public final class TIgnored extends Token
{
    public TIgnored()
    {
        super.setText("Ignored");
    }

    public TIgnored(int line, int pos)
    {
        super.setText("Ignored");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIgnored(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIgnored(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TIgnored text.");
    }
}
