/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.TLAbkt;
import org.sablecc.sablecc.node.Token;



public final class TLAbkt extends Token
{
    public TLAbkt()
    {
        super.setText("<");
    }

    public TLAbkt(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLAbkt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLAbkt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLAbkt text.");
    }
}
