/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.TRAbkt;
import org.sablecc.sablecc.node.Token;



public final class TRAbkt extends Token
{
    public TRAbkt()
    {
        super.setText(">");
    }

    public TRAbkt(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRAbkt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRAbkt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRAbkt text.");
    }
}
