/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;
import org.sablecc.sablecc.node.Node;
import org.sablecc.sablecc.node.PIdListTail;
import org.sablecc.sablecc.node.Switch;
import org.sablecc.sablecc.node.XPIdListTail;

public final class X1PIdListTail extends XPIdListTail
{
    private XPIdListTail _xPIdListTail_;
    private PIdListTail _pIdListTail_;

    public X1PIdListTail()
    {
    }

    public X1PIdListTail(
        XPIdListTail _xPIdListTail_,
        PIdListTail _pIdListTail_)
    {
        setXPIdListTail(_xPIdListTail_);
        setPIdListTail(_pIdListTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPIdListTail getXPIdListTail()
    {
        return _xPIdListTail_;
    }

    public void setXPIdListTail(XPIdListTail node)
    {
        if(_xPIdListTail_ != null)
        {
            _xPIdListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPIdListTail_ = node;
    }

    public PIdListTail getPIdListTail()
    {
        return _pIdListTail_;
    }

    public void setPIdListTail(PIdListTail node)
    {
        if(_pIdListTail_ != null)
        {
            _pIdListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pIdListTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPIdListTail_ == child)
        {
            _xPIdListTail_ = null;
        }

        if(_pIdListTail_ == child)
        {
            _pIdListTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPIdListTail_) +
            toString(_pIdListTail_);
    }
}
