/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class ATransition extends PTransition
{
    private TRArrow _rArrow_;
    private TId _id_;

    public ATransition()
    {
    }

    public ATransition(
        TRArrow _rArrow_,
        TId _id_)
    {
        setRArrow(_rArrow_);

        setId(_id_);

    }
    public Object clone()
    {
        return new ATransition(
            (TRArrow) cloneNode(_rArrow_),
            (TId) cloneNode(_id_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATransition(this);
    }

    public TRArrow getRArrow()
    {
        return _rArrow_;
    }

    public void setRArrow(TRArrow node)
    {
        if(_rArrow_ != null)
        {
            _rArrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rArrow_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_rArrow_)
            + toString(_id_);
    }

    void removeChild(Node child)
    {
        if(_rArrow_ == child)
        {
            _rArrow_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_rArrow_ == oldChild)
        {
            setRArrow((TRArrow) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

    }
}
