/*
Copyright (C) 2000  Steffen Zschaler

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/*
 * CollectionEditor.java
 *
 * Created on 10. August 2000, 15:38
 */
 
package tudresden.ocl.injection.reverseeng;

/** 
  * Editor pane for collection element types.
  *
  * @author  sz9 (Steffen Zschaler)
  * @version 0.1
  */
public class CollectionEditor extends javax.swing.JPanel {

  private CollectionDescriptor m_cdModel;
  private TypeComboModel m_tcmElementTypeModel;
  private boolean m_fEditingStarted = false;  
  
  /** Creates new form CollectionEditor */
  public CollectionEditor (CollectionDescriptor cdModel) {
    super();
    
    m_cdModel = cdModel;    
    
    String sElementType = m_cdModel.getElementType();
    
    initComponents ();
        
    m_jtaDocComment.setText (m_cdModel.getCleanedComment());
    m_jcbElementType.setSelectedItem (sElementType);
    
    // Allow edits to propagate
    m_fEditingStarted = true;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    m_jspDocComment = new javax.swing.JScrollPane ();
    m_jtaDocComment = new javax.swing.JTextArea ();
    m_jlElementTypePrompt = new javax.swing.JLabel ();
    m_jcbElementType = new javax.swing.JComboBox ();
    setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints1;


      m_jtaDocComment.setToolTipText ("The JavaDoc comment associated with the collection.");
      m_jtaDocComment.setBackground (java.awt.Color.lightGray);
      m_jtaDocComment.setEditable (false);
  
      m_jspDocComment.setViewportView (m_jtaDocComment);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridwidth = 0;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints1.weightx = 2.0;
    gridBagConstraints1.weighty = 3.0;
    add (m_jspDocComment, gridBagConstraints1);

    m_jlElementTypePrompt.setText ("Element Type:");


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints1.weightx = 1.0;
    add (m_jlElementTypePrompt, gridBagConstraints1);

    m_jcbElementType.setToolTipText ("Enter type of collection elements.\nThe dropdown box contains suggestions and standard types.");
    m_tcmElementTypeModel = new TypeComboModel() {
      public void setSelectedItem (Object oSelectedItem) {
        super.setSelectedItem (oSelectedItem);

        if (m_fEditingStarted) {
          m_cdModel.setElementType ((String) getSelectedItem());
        }
      }
    };
    m_jcbElementType.setModel (m_tcmElementTypeModel);
    m_jcbElementType.setEditable (true);


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridwidth = 0;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints1.weightx = 1.0;
    add (m_jcbElementType, gridBagConstraints1);

  }//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane m_jspDocComment;
  private javax.swing.JTextArea m_jtaDocComment;
  private javax.swing.JLabel m_jlElementTypePrompt;
  private javax.swing.JComboBox m_jcbElementType;
  // End of variables declaration//GEN-END:variables

}