/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AAndLogicalOperator extends PLogicalOperator
{
    private TAnd _and_;

    public AAndLogicalOperator()
    {
    }

    public AAndLogicalOperator(
        TAnd _and_)
    {
        setAnd(_and_);

    }
    public Object clone()
    {
        return new AAndLogicalOperator(
            (TAnd) cloneNode(_and_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndLogicalOperator(this);
    }

    public TAnd getAnd()
    {
        return _and_;
    }

    public void setAnd(TAnd node)
    {
        if(_and_ != null)
        {
            _and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _and_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_and_);
    }

    void removeChild(Node child)
    {
        if(_and_ == child)
        {
            _and_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

    }
}

