/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AArrowPostfixExpressionTailBegin extends PPostfixExpressionTailBegin
{
    private TArrow _arrow_;

    public AArrowPostfixExpressionTailBegin()
    {
    }

    public AArrowPostfixExpressionTailBegin(
        TArrow _arrow_)
    {
        setArrow(_arrow_);

    }
    public Object clone()
    {
        return new AArrowPostfixExpressionTailBegin(
            (TArrow) cloneNode(_arrow_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrowPostfixExpressionTailBegin(this);
    }

    public TArrow getArrow()
    {
        return _arrow_;
    }

    public void setArrow(TArrow node)
    {
        if(_arrow_ != null)
        {
            _arrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _arrow_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_arrow_);
    }

    void removeChild(Node child)
    {
        if(_arrow_ == child)
        {
            _arrow_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_arrow_ == oldChild)
        {
            setArrow((TArrow) newChild);
            return;
        }

    }
}
