/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class ACollectionTypeName extends PTypeName
{
    private PCollectionType _collectionType_;
    private TLPar _lPar_;
    private TSimpleTypeName _simpleTypeName_;
    private TRPar _rPar_;

    public ACollectionTypeName()
    {
    }

    public ACollectionTypeName(
        PCollectionType _collectionType_,
        TLPar _lPar_,
        TSimpleTypeName _simpleTypeName_,
        TRPar _rPar_)
    {
        setCollectionType(_collectionType_);

        setLPar(_lPar_);

        setSimpleTypeName(_simpleTypeName_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new ACollectionTypeName(
            (PCollectionType) cloneNode(_collectionType_),
            (TLPar) cloneNode(_lPar_),
            (TSimpleTypeName) cloneNode(_simpleTypeName_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionTypeName(this);
    }

    public PCollectionType getCollectionType()
    {
        return _collectionType_;
    }

    public void setCollectionType(PCollectionType node)
    {
        if(_collectionType_ != null)
        {
            _collectionType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _collectionType_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public TSimpleTypeName getSimpleTypeName()
    {
        return _simpleTypeName_;
    }

    public void setSimpleTypeName(TSimpleTypeName node)
    {
        if(_simpleTypeName_ != null)
        {
            _simpleTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _simpleTypeName_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_collectionType_)
            + toString(_lPar_)
            + toString(_simpleTypeName_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_collectionType_ == child)
        {
            _collectionType_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_simpleTypeName_ == child)
        {
            _simpleTypeName_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_collectionType_ == oldChild)
        {
            setCollectionType((PCollectionType) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_simpleTypeName_ == oldChild)
        {
            setSimpleTypeName((TSimpleTypeName) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
