/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AConstraintBody extends PConstraintBody
{
    private PStereotype _stereotype_;
    private TName _name_;
    private TColon _colon_;
    private PExpression _expression_;

    public AConstraintBody()
    {
    }

    public AConstraintBody(
        PStereotype _stereotype_,
        TName _name_,
        TColon _colon_,
        PExpression _expression_)
    {
        setStereotype(_stereotype_);

        setName(_name_);

        setColon(_colon_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AConstraintBody(
            (PStereotype) cloneNode(_stereotype_),
            (TName) cloneNode(_name_),
            (TColon) cloneNode(_colon_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstraintBody(this);
    }

    public PStereotype getStereotype()
    {
        return _stereotype_;
    }

    public void setStereotype(PStereotype node)
    {
        if(_stereotype_ != null)
        {
            _stereotype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stereotype_ = node;
    }

    public TName getName()
    {
        return _name_;
    }

    public void setName(TName node)
    {
        if(_name_ != null)
        {
            _name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _name_ = node;
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stereotype_)
            + toString(_name_)
            + toString(_colon_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_stereotype_ == child)
        {
            _stereotype_ = null;
            return;
        }

        if(_name_ == child)
        {
            _name_ = null;
            return;
        }

        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stereotype_ == oldChild)
        {
            setStereotype((PStereotype) newChild);
            return;
        }

        if(_name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}

