/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AEnumerationTypeTail extends PEnumerationTypeTail
{
    private TComma _comma_;
    private TChannel _channel_;
    private TName _name_;

    public AEnumerationTypeTail()
    {
    }

    public AEnumerationTypeTail(
        TComma _comma_,
        TChannel _channel_,
        TName _name_)
    {
        setComma(_comma_);

        setChannel(_channel_);

        setName(_name_);

    }
    public Object clone()
    {
        return new AEnumerationTypeTail(
            (TComma) cloneNode(_comma_),
            (TChannel) cloneNode(_channel_),
            (TName) cloneNode(_name_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumerationTypeTail(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public TChannel getChannel()
    {
        return _channel_;
    }

    public void setChannel(TChannel node)
    {
        if(_channel_ != null)
        {
            _channel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _channel_ = node;
    }

    public TName getName()
    {
        return _name_;
    }

    public void setName(TName node)
    {
        if(_name_ != null)
        {
            _name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _name_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_channel_)
            + toString(_name_);
    }

    void removeChild(Node child)
    {
        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_channel_ == child)
        {
            _channel_ = null;
            return;
        }

        if(_name_ == child)
        {
            _name_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_channel_ == oldChild)
        {
            setChannel((TChannel) newChild);
            return;
        }

        if(_name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

    }
}

