/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AEqualRelationalOperator extends PRelationalOperator
{
    private TEqual _equal_;

    public AEqualRelationalOperator()
    {
    }

    public AEqualRelationalOperator(
        TEqual _equal_)
    {
        setEqual(_equal_);

    }
    public Object clone()
    {
        return new AEqualRelationalOperator(
            (TEqual) cloneNode(_equal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualRelationalOperator(this);
    }

    public TEqual getEqual()
    {
        return _equal_;
    }

    public void setEqual(TEqual node)
    {
        if(_equal_ != null)
        {
            _equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _equal_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_equal_);
    }

    void removeChild(Node child)
    {
        if(_equal_ == child)
        {
            _equal_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

    }
}
