/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AInvStereotype extends PStereotype
{
    private TTInv _tInv_;

    public AInvStereotype()
    {
    }

    public AInvStereotype(
        TTInv _tInv_)
    {
        setTInv(_tInv_);

    }
    public Object clone()
    {
        return new AInvStereotype(
            (TTInv) cloneNode(_tInv_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInvStereotype(this);
    }

    public TTInv getTInv()
    {
        return _tInv_;
    }

    public void setTInv(TTInv node)
    {
        if(_tInv_ != null)
        {
            _tInv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tInv_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tInv_);
    }

    void removeChild(Node child)
    {
        if(_tInv_ == child)
        {
            _tInv_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tInv_ == oldChild)
        {
            setTInv((TTInv) newChild);
            return;
        }

    }
}

