/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class ANonCollectionTypeName extends PTypeName
{
    private TSimpleTypeName _simpleTypeName_;

    public ANonCollectionTypeName()
    {
    }

    public ANonCollectionTypeName(
        TSimpleTypeName _simpleTypeName_)
    {
        setSimpleTypeName(_simpleTypeName_);

    }
    public Object clone()
    {
        return new ANonCollectionTypeName(
            (TSimpleTypeName) cloneNode(_simpleTypeName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonCollectionTypeName(this);
    }

    public TSimpleTypeName getSimpleTypeName()
    {
        return _simpleTypeName_;
    }

    public void setSimpleTypeName(TSimpleTypeName node)
    {
        if(_simpleTypeName_ != null)
        {
            _simpleTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _simpleTypeName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_simpleTypeName_);
    }

    void removeChild(Node child)
    {
        if(_simpleTypeName_ == child)
        {
            _simpleTypeName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_simpleTypeName_ == oldChild)
        {
            setSimpleTypeName((TSimpleTypeName) newChild);
            return;
        }

    }
}
