/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class AOrLogicalOperator extends PLogicalOperator
{
    private TOr _or_;

    public AOrLogicalOperator()
    {
    }

    public AOrLogicalOperator(
        TOr _or_)
    {
        setOr(_or_);

    }
    public Object clone()
    {
        return new AOrLogicalOperator(
            (TOr) cloneNode(_or_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrLogicalOperator(this);
    }

    public TOr getOr()
    {
        return _or_;
    }

    public void setOr(TOr node)
    {
        if(_or_ != null)
        {
            _or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _or_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_or_);
    }

    void removeChild(Node child)
    {
        if(_or_ == child)
        {
            _or_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

    }
}

