/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class APostfixExpressionTail extends PPostfixExpressionTail
{
    private PPostfixExpressionTailBegin _postfixExpressionTailBegin_;
    private PFeatureCall _featureCall_;

    public APostfixExpressionTail()
    {
    }

    public APostfixExpressionTail(
        PPostfixExpressionTailBegin _postfixExpressionTailBegin_,
        PFeatureCall _featureCall_)
    {
        setPostfixExpressionTailBegin(_postfixExpressionTailBegin_);

        setFeatureCall(_featureCall_);

    }
    public Object clone()
    {
        return new APostfixExpressionTail(
            (PPostfixExpressionTailBegin) cloneNode(_postfixExpressionTailBegin_),
            (PFeatureCall) cloneNode(_featureCall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostfixExpressionTail(this);
    }

    public PPostfixExpressionTailBegin getPostfixExpressionTailBegin()
    {
        return _postfixExpressionTailBegin_;
    }

    public void setPostfixExpressionTailBegin(PPostfixExpressionTailBegin node)
    {
        if(_postfixExpressionTailBegin_ != null)
        {
            _postfixExpressionTailBegin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _postfixExpressionTailBegin_ = node;
    }

    public PFeatureCall getFeatureCall()
    {
        return _featureCall_;
    }

    public void setFeatureCall(PFeatureCall node)
    {
        if(_featureCall_ != null)
        {
            _featureCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _featureCall_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_postfixExpressionTailBegin_)
            + toString(_featureCall_);
    }

    void removeChild(Node child)
    {
        if(_postfixExpressionTailBegin_ == child)
        {
            _postfixExpressionTailBegin_ = null;
            return;
        }

        if(_featureCall_ == child)
        {
            _featureCall_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_postfixExpressionTailBegin_ == oldChild)
        {
            setPostfixExpressionTailBegin((PPostfixExpressionTailBegin) newChild);
            return;
        }

        if(_featureCall_ == oldChild)
        {
            setFeatureCall((PFeatureCall) newChild);
            return;
        }

    }
}

