/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class APreStereotype extends PStereotype
{
    private TTPre _tPre_;

    public APreStereotype()
    {
    }

    public APreStereotype(
        TTPre _tPre_)
    {
        setTPre(_tPre_);

    }
    public Object clone()
    {
        return new APreStereotype(
            (TTPre) cloneNode(_tPre_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreStereotype(this);
    }

    public TTPre getTPre()
    {
        return _tPre_;
    }

    public void setTPre(TTPre node)
    {
        if(_tPre_ != null)
        {
            _tPre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tPre_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tPre_);
    }

    void removeChild(Node child)
    {
        if(_tPre_ == child)
        {
            _tPre_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tPre_ == oldChild)
        {
            setTPre((TTPre) newChild);
            return;
        }

    }
}

