/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import java.util.*;
import tudresden.ocl.parser.analysis.*;

public final class ATypeNamePathNameEnd extends PPathNameEnd
{
    private PTypeName _typeName_;

    public ATypeNamePathNameEnd()
    {
    }

    public ATypeNamePathNameEnd(
        PTypeName _typeName_)
    {
        setTypeName(_typeName_);

    }
    public Object clone()
    {
        return new ATypeNamePathNameEnd(
            (PTypeName) cloneNode(_typeName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeNamePathNameEnd(this);
    }

    public PTypeName getTypeName()
    {
        return _typeName_;
    }

    public void setTypeName(PTypeName node)
    {
        if(_typeName_ != null)
        {
            _typeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _typeName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_typeName_);
    }

    void removeChild(Node child)
    {
        if(_typeName_ == child)
        {
            _typeName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_typeName_ == oldChild)
        {
            setTypeName((PTypeName) newChild);
            return;
        }

    }
}

