/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class TDcolon extends Token
{
    public TDcolon()
    {
        super.setText("::");
    }

    public TDcolon(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDcolon(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDcolon(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDcolon text.");
    }
}

