/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class TNEqual extends Token
{
    public TNEqual()
    {
        super.setText("<>");
    }

    public TNEqual(int line, int pos)
    {
        super.setText("<>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNEqual text.");
    }
}

