/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class TTPost extends Token
{
    public TTPost()
    {
        super.setText("post");
    }

    public TTPost(int line, int pos)
    {
        super.setText("post");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTPost(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPost(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTPost text.");
    }
}

