/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class TXor extends Token
{
    public TXor()
    {
        super.setText("xor");
    }

    public TXor(int line, int pos)
    {
        super.setText("xor");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXor text.");
    }
}
