/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class X1PEnumerationTypeTail extends XPEnumerationTypeTail
{
    private XPEnumerationTypeTail _xPEnumerationTypeTail_;
    private PEnumerationTypeTail _pEnumerationTypeTail_;

    public X1PEnumerationTypeTail()
    {
    }

    public X1PEnumerationTypeTail(
        XPEnumerationTypeTail _xPEnumerationTypeTail_,
        PEnumerationTypeTail _pEnumerationTypeTail_)
    {
        setXPEnumerationTypeTail(_xPEnumerationTypeTail_);
        setPEnumerationTypeTail(_pEnumerationTypeTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPEnumerationTypeTail getXPEnumerationTypeTail()
    {
        return _xPEnumerationTypeTail_;
    }

    public void setXPEnumerationTypeTail(XPEnumerationTypeTail node)
    {
        if(_xPEnumerationTypeTail_ != null)
        {
            _xPEnumerationTypeTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPEnumerationTypeTail_ = node;
    }

    public PEnumerationTypeTail getPEnumerationTypeTail()
    {
        return _pEnumerationTypeTail_;
    }

    public void setPEnumerationTypeTail(PEnumerationTypeTail node)
    {
        if(_pEnumerationTypeTail_ != null)
        {
            _pEnumerationTypeTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pEnumerationTypeTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPEnumerationTypeTail_ == child)
        {
            _xPEnumerationTypeTail_ = null;
        }

        if(_pEnumerationTypeTail_ == child)
        {
            _pEnumerationTypeTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPEnumerationTypeTail_) +
            toString(_pEnumerationTypeTail_);
    }
}
