/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class X2PDeclaratorTail extends XPDeclaratorTail
{
    private PDeclaratorTail _pDeclaratorTail_;

    public X2PDeclaratorTail()
    {
    }

    public X2PDeclaratorTail(
        PDeclaratorTail _pDeclaratorTail_)
    {
        setPDeclaratorTail(_pDeclaratorTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PDeclaratorTail getPDeclaratorTail()
    {
        return _pDeclaratorTail_;
    }

    public void setPDeclaratorTail(PDeclaratorTail node)
    {
        if(_pDeclaratorTail_ != null)
        {
            _pDeclaratorTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pDeclaratorTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_pDeclaratorTail_ == child)
        {
            _pDeclaratorTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pDeclaratorTail_);
    }
}

