/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package tudresden.ocl.parser.node;

import tudresden.ocl.parser.analysis.*;

public final class X2PPostfixExpressionTail extends XPPostfixExpressionTail
{
    private PPostfixExpressionTail _pPostfixExpressionTail_;

    public X2PPostfixExpressionTail()
    {
    }

    public X2PPostfixExpressionTail(
        PPostfixExpressionTail _pPostfixExpressionTail_)
    {
        setPPostfixExpressionTail(_pPostfixExpressionTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PPostfixExpressionTail getPPostfixExpressionTail()
    {
        return _pPostfixExpressionTail_;
    }

    public void setPPostfixExpressionTail(PPostfixExpressionTail node)
    {
        if(_pPostfixExpressionTail_ != null)
        {
            _pPostfixExpressionTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pPostfixExpressionTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_pPostfixExpressionTail_ == child)
        {
            _pPostfixExpressionTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pPostfixExpressionTail_);
    }
}

