/* Generated by Together */

package com.togethersoft.modules.ocl.test.testmodel;

/**
 * The bidirectional association between SelectedClass and this class originally originated from this class. The transformation to bidirectional has been made by applying the respective pattern onto it. 
 */
public class NamedBidirectionalAssociation {
    /**
     * @bidirectional <{com.togethersoft.modules.ocl.test.testmodel.ClassInSamePackage#lnkrevNamedBidirectionalAssociation}>
     * @clientRole someRolename 
     */
    private ClassInSamePackage lnkClassInSamePackage;

    /**
     * @bidirectional <{com.togethersoft.modules.ocl.test.testmodel.SelectedClass#lnkrevNamedBidirectionalAssociation}>
     * @clientRole secondRolename
     */
    private SelectedClass lnkSelectedClass;
}
