package university // this is the package name 
        university // this is the namespace prefix
        "http://www.emftext.org/language/university" {

	class University {
		containment reference Student students (1..-1);
		containment reference Employee employees (1..-1);
	}
	
	class Person {
		attribute EString firstName (1..1);
		attribute EString lastName (1..1);
		attribute EBoolean isMarried (1..1);
		attribute Date birthDate (1..1);
		attribute EInt age (1..1);
		attribute EInt salaries (1..-1);
		reference Person supervisor (0..1) opposite supervised;
		reference Person supervised (0..-1) opposite supervisor;
	}
	
	class Student extends Person {
		attribute EInt matNr (1..1);
		attribute Date matDate (1..1);
	}
	
	class Employee extends Person {
		attribute EString soSecNr (1..1);
		attribute EString taxClass (1..1);
		attribute EInt wage (1..1);
	}
	
	class PhDStudent extends Employee {
		attribute EString dissSubject (1..1);
	}
	
	datatype Date "java.util.Date"
}
